//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Food_Final
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFavorite
    {
        public int UserID { get; set; }
        public int RecipeID { get; set; }
    
        public virtual Recipe Recipe { get; set; }
        public virtual Recipe Recipe1 { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual UserProfile UserProfile1 { get; set; }
    }
}
